### ISSUE TITLE
Wrong document for "CUDA Kernels with C++"

### ISSUE THREAD

**Issue by JPenuchot** [CppCon/CppCon2018#2]
The ["PDF" document](https://raw.githubusercontent.com/CppCon/CppCon2018/master/Presentations/cuda_kernels_with_cpp/cuda_kernels_with_cpp__michael_gopshtein__cppcon_2018.pdf) in the repo actually is the GitHub [web view of the PDF document](https://github.com/mgopshtein/cudacpp/blob/master/docs/CUDA%20Kernels%20with%20C%2B%2B%20-%20Michael%20Gopshtein%20-%20CppCon%202018.pdf)

**Comment by kernhanda** [comment]
Fixed. Thanks for reporting.
