### ISSUE TITLE
Missing Slides: Alan Talbot “Moving Faster: Everyday efficiency in modern C++”

### ISSUE THREAD

**Issue by kaihowl** [CppCon/CppCon2018#4]
I can find the presentation on [YouTube](https://www.youtube.com/watch?v=EovBkh9wDnM), yet I cannot find the slides in this repo.

**Comment by pqant** [comment]
I'm not sure whether it's late or not for this however I added the slide's link that you're looking for. 

https://github.com/boostcon/cppnow_presentations_2018/blob/master/05-08-2018_tuesday/moving_faster__everyday_efficiency_in_modern_cpp__cppnow_05082018.pdf

**Comment by kaihowl** [comment]
Thank you, @pqant!
